print("git log -n 3")
print("git log --help")
print("git log --oneline")
print("git status")
print("git branch")
print("git branch dev")
print("git checkout dev")
print("")
print("")
print("")
print("Git 提示fatal: remote origin already exists")
print("先删除远程 Git 仓库$ git remote rm origin")
print("2、再添加远程 Git 仓库$ git remote add origin git@github.com:FBing/java-code-generator")
print("")
print("")
print("")
print("解决:git push error: failed to push some refs to")
print("使用如下命令：git pull --rebase origin master")
print("然后再进行上传: git push -u origin master")
print("")
print("")
print("")
print("git 提交出现这个错误fatal: Unable to create ‘project_path/.git/index.lock’: File exists. exists")
print("rm -f ./.git/index.lock")
print("")
print("")
print("")
print("只推送仓库本身，而不推送任何 LFS 对象")
print("git push --no-verify backup master")
print("git push --no-verify origin main")
print("")
print("")
print("")
print("")
print("")
