print("git init")
print("")
print("git add .")
print("")
print("git commit -m '描述信息'")
print("")
print("查看git管理文件的状态")
print("git status")
print("")
print("查看版本")
print("git log")
print("")
print("创建分支")
print("git branch 分支的名字")
print("")
print("切换分支")
print("git checkout 分支的名字")
print("")
print("分支的合并")
print("git merge")
print("")
print("")
print("")
print("")
print("")
print("")
