print("git config --global user.name 'mirana'")
print()
print("git config --global user.email ''")
print()
print()
print("个人编译器")
print("在windows系统下，如果你想用notepad++文本编译器用作当Git需要输入消息的时候的话。")
print("在x86系统上")
print()
print("""git config --global core.editor "'C:/Program Files/Notepad++.exe' -multiInst -nosession""""")
print()
print("在x64系统上")
print("""git config --global core.editor "'C:/Program Files(x86)/Notepad++.exe' -multiInst""""")
print("书上这两个代码上下对调出错？")
